wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1716384585
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 23
      4: 3.9.5
      5: 0.17.0
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
