# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: null
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

storage_location: 'logs/hessian_values'
batch_size: 16
percentage_data: None
weight_decay: None
top_k: 5
tol: 1e-3
max_iter: 1000
cuda: False
verbose: True

# passing checkpoint path dict is necessary for computation 
ckpt_path_dict: ???




