# @package _global_

# runs with execution time profiling

defaults:
  - default

trainer:
  max_epochs: 1
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2
  fast_dev_run: true
  # profiler: "simple"
  # profiler: "advanced"
  profiler: "pytorch"

