_target_: src.models.wang2022_module.Wang2022LightningModule

# DO NOT CHANGE THIS FILE, OVERWRITE model.net IN THE EXPERIMENT
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0004
  betas: [0.9, 0.999]

# DO NOT CHANGE THIS FILE, OVERWRITE model.net IN THE EXPERIMENT
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 1
  gamma: 0.9

# DO NOT CHANGE THIS FILE, OVERWRITE model.net IN THE EXPERIMENT
net:
  _target_: src.models.components.wang2022.rsteer.Relaxed_Rot_SteerConvNet
  in_frames: 10
  out_frames: 1
  hidden_dim: 32
  kernel_size: 3 
  num_layers: 5
  N: 4
  alpha: 0

# compile model for faster training with pytorch 2.0
compile: false
